# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180414_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pics',
            name='pic',
        ),
        migrations.AlterField(
            model_name='pics',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
